### ISSUE TITLE
Getting converse error everytime.

### ISSUE THREAD

**Issue by rahul-bedarkar** [androidthings/sample-googleassistant#51]
Please find logs. 

01-11 11:03:25.330 15138-15138/? I/zygote: Late-enabling -Xcheck:jni
01-11 11:03:25.479 15138-15138/? W/zygote: Using default instruction set features for ARM CPU variant (generic) using conservative defaults
01-11 11:03:26.879 15138-15138/com.example.androidthings.assistant I/InstantRun: starting instant run server: is main process
01-11 11:03:27.027 15138-15138/com.example.androidthings.assistant I/AssistantActivity: starting assistant demo
01-11 11:03:27.499 15138-15138/com.example.androidthings.assistant I/AssistantActivity: initializing DAC trigger
01-11 11:03:27.581 15138-15138/com.example.androidthings.assistant I/AssistantActivity: setting audio track volume to: 100
01-11 11:03:28.064 15138-15138/com.example.androidthings.assistant D/NetworkSecurityConfig: No Network Security Config specified, using platform default
01-11 11:03:28.543 15138-15138/com.example.androidthings.assistant D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
01-11 11:03:28.689 15138-15138/com.example.androidthings.assistant D/OpenGLRenderer: HWUI GL Pipeline
01-11 11:03:50.730 15138-15144/com.example.androidthings.assistant I/zygote: Do partial code cache collection, code=29KB, data=29KB
01-11 11:03:50.744 15138-15144/com.example.androidthings.assistant I/zygote: After code cache collection, code=29KB, data=29KB
01-11 11:03:50.744 15138-15144/com.example.androidthings.assistant I/zygote: Increasing code cache capacity to 128KB
01-11 11:03:51.678 15138-15138/com.example.androidthings.assistant I/AssistantActivity: starting assistant request, enable microphones
01-11 11:04:00.277 15138-15138/com.example.androidthings.assistant D/AssistantActivity: converse response event: END_OF_UTTERANCE
01-11 11:04:00.559 15138-15144/com.example.androidthings.assistant I/zygote: Do partial code cache collection, code=60KB, data=61KB
01-11 11:04:00.563 15138-15144/com.example.androidthings.assistant I/zygote: After code cache collection, code=60KB, data=61KB
01-11 11:04:00.563 15138-15144/com.example.androidthings.assistant I/zygote: Increasing code cache capacity to 256KB
01-11 11:05:00.228 15138-15138/com.example.androidthings.assistant E/AssistantActivity: converse error
                                                                                        io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
                                                                                            at io.grpc.Status.asRuntimeException(Status.java:540)
                                                                                            at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
                                                                                            at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
                                                                                            at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
                                                                                            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
                                                                                            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
                                                                                            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
                                                                                            at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
                                                                                            at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                            at java.lang.Thread.run(Thread.java:764)
01-11 11:05:00.345 15138-15144/com.example.androidthings.assistant I/zygote: Do full code cache collection, code=124KB, data=99KB
01-11 11:05:00.349 15138-15144/com.example.androidthings.assistant I/zygote: After code cache collection, code=98KB, data=63KB

**Comment by Fleker** [comment]
Is this with the most recent version of the project?

Are you sure you have an Internet connection? I see your date is correct, but was that set after the app was initialized? There may be SSL errors early in your logs.

**Comment by rahul-bedarkar** [comment]
I am running latest version.

I can ping www.google.com. On google cloud project - I can see all errors for Google assistant APIs. I don't see SSL errors for this applications in logs.

**Comment by rahul-bedarkar** [comment]
There is one error before ethernet connection is established. 

01-01 00:00:13.461 297-1145/system_process D/NetworkMonitor/NetworkAgentInfo [Ethernet () - 100]: PROBE_HTTPS https://www.google.com/generate_204 Probe failed with exception javax.net.ssl.SSLHandshakeException: Unacceptable certificate: CN=Google Internet Authority G2, O=Google Inc, C=US
01-01 00:00:13.927 815-949/com.google.android.gms E/ProcessCheckinRequest: SSL error, attempting time correction: javax.net.ssl.SSLHandshakeException: Unacceptable certificate: CN=Google Internet Authority G2, O=Google Inc, C=US

Once internet is available and date is synced there is no SSL error. I am loading application using Android Studio.

**Comment by Fleker** [comment]
Can you stop the app and restart once data is synced and see if it still works?
