### ISSUE TITLE
so bad

### ISSUE THREAD

**Issue by Wc30** [androidthings/sample-googleassistant#72]

**Comment by Wc30** [comment]
When I run studio, I only show the NEW REQUEST button.

**Comment by Fleker** [comment]
You need to connect to Internet. You can see that the date is incorrect as well.

**Comment by Wc30** [comment]
Change my raspberry pie time?I feel a little dizzy.Maybe my buttons are not on the breadboard.

**Comment by Wc30** [comment]
I don't have a button on my breadboard yet, you're talking about the time the raspberry pie shows.



------------------ 原始邮件 ------------------
发件人: "Nick"<notifications@github.com>;
发送时间: 2018年5月8日(星期二) 凌晨0:48
收件人: "androidthings/sample-googleassistant"<sample-googleassistant@noreply.github.com>;
抄送: "回忆"<2506314816@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [androidthings/sample-googleassistant] so bad (#72)




You need to connect to Internet. You can see that the date is incorrect as well.

**Comment by Fleker** [comment]
If your device is not connected to the Internet, it will not connect to an [NTP server](https://en.wikipedia.org/wiki/Network_Time_Protocol), and HTTPS requests will fail.

**Comment by Wc30** [comment]
So what should I do?I mean how to get my device to connect to the network, my raspberry pie has been connected to wiff.What do you mean by not connecting to the Internet?

**Comment by Wc30** [comment]
![21e8bf7bcf853937439a038e2fd86a2](https://user-images.githubusercontent.com/34146988/39736888-043b9fb6-52b5-11e8-8aa9-77ba114be78d.png)
![b01f99303afacd7b261d2ec825e6ad3](https://user-images.githubusercontent.com/34146988/39736904-13a2cdc6-52b5-11e8-8d6c-f127ce85340b.png)

![db1da9d9e04fc44978cf9a02716cd7c](https://user-images.githubusercontent.com/34146988/39736915-1cf94f9e-52b5-11e8-99ae-0c15d719ef1c.png)

**Comment by Wc30** [comment]
01-01 00:09:41.779 732-1511/com.google.android.gms.persistent E/Uploader: Clearcut transport failed to make network request.
                                                                          java.net.SocketTimeoutException: failed to connect to play.googleapis.com/216.58.199.10 (port 443) from /192.168.1.96 (port 38906) after 60000ms
                                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
                                                                              at libcore.io.IoBridge.connect(IoBridge.java:130)
                                                                              at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
                                                                              at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
                                                                              at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
                                                                              at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
                                                                              at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
                                                                              at java.net.Socket.connect(Socket.java:616)
                                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
                                                                              at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
                                                                              at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                              at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                              at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                              at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
                                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
                                                                              at pvg.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):61)
                                                                              at pvg.execute(:com.google.android.gms@12520015@12.5.20 (030300-189423146):8)
                                                                              at pvg.execute(:com.google.android.gms@12520015@12.5.20 (030300-189423146):7)
                                                                              at jup.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):10)
                                                                              at jup.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):48)
                                                                              at jve.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):145)
                                                                              at jve.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):190)
                                                                              at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.c(:com.google.android.gms@12520015@12.5.20 (030300-189423146):44)
                                                                              at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):19)
                                                                              at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.a(:com.google.android.gms@12520015@12.5.20 (030300-189423146):8)
                                                                              at pai.run(:com.google.android.gms@12520015@12.5.20 (030300-189423146):1)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                              at java.lang.Thread.run(Thread.java:764)
01-01 00:09:41.790 732-1511/com.google.android.gms.persistent E/NetworkScheduler.ATC: Trying to release unacquired lock: com.google.android.gms/.clearcut.uploader.QosUploaderService

**Comment by Fleker** [comment]
Add an ethernet or Wi-Fi connection so that it will connect to the Internet, get the current time, and allow it to make HTTPS requests.

**Comment by Wc30** [comment]
I'm sorry to bother you all the time, but I have to wiff all the time.I don't even have the Internet because I'm a over the wall link to the Google interface.
To why?

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39791024-bd86908c-536b-11e8-8117-daf00d1f20a5.png)

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39791150-abe0a5d8-536c-11e8-8e40-b8c19603ee0f.png)

**Comment by Fleker** [comment]
The Google Assistant API is a cloud API. You need to make calls through an Internet connection.

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39791606-2996be66-536f-11e8-820b-ff266fe77796.png)

**Comment by Wc30** [comment]
Make a call?Call who?Or dial-up access.

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39791676-8f32337c-536f-11e8-8b4f-2aaf11610501.png)
It stops here, is it wrong or is it right?What's wrong? What's wrong?

**Comment by Wc30** [comment]
![Uploading image.png…]()

**Comment by Fleker** [comment]
Nothing seems wrong with your posted logs. It seems like your device is connected to the Internet. Have you tried sending a command? You can press the button on-screen or if you've connected it.

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39847015-d2a8f2fe-5431-11e8-95b0-af53d772f261.png)

**Comment by Wc30** [comment]
![image](https://user-images.githubusercontent.com/34146988/39849713-51196688-5440-11e8-8721-362bd89c1248.png)
ok？

**Comment by Fleker** [comment]
![this log](https://user-images.githubusercontent.com/34146988/39847015-d2a8f2fe-5431-11e8-95b0-af53d772f261.png)

This is the most important error. It states that the app cannot make a secure connection to the Google Assistant because the time is wrong (see 01-01? That's January 1st, which is not today.) Usually the time is not up to date because your device is not connected to the Internet. Until you get the time updated, the app will fail to load.

**Comment by Wc30** [comment]
So you think there is no connection to the Internet?
![image](https://user-images.githubusercontent.com/34146988/39854388-1adf4d8e-545a-11e8-9f05-c9ac6d4eef26.png)

A new problem has arisen.
![image](https://user-images.githubusercontent.com/34146988/39854365-feadb5ba-5459-11e8-977a-9384511a4538.png)

**Comment by Fleker** [comment]
I don't know whether the device is connected or not, but it has not updated the system time.

**Comment by Wc30** [comment]
Ok, I will continue to check whether the time has been modified,

**Comment by 16372212** [comment]
i meet the same question, have you already handled this problem?

**Comment by CometInfosoft** [comment]
Not, yet Mr. John. have you ?

**Comment by Wc30** [comment]
Because my Androidthings can't over the wall
