### ISSUE TITLE
Failed resolution of: Lcom/google/android/things/pio/PeripheralManager;

### ISSUE THREAD

**Issue by CometInfosoft** [androidthings/sample-googleassistant#86]

**Comment by CometInfosoft** [comment]
--------- beginning of crash
2018-10-21 06:36:47.230 6992-6992/com.example.androidthings.assistant E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androidthings.assistant, PID: 6992
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/things/pio/PeripheralManager;
        at com.example.androidthings.assistant.AssistantActivity.onCreate(AssistantActivity.java:146)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.things.pio.PeripheralManager" on path: DexPathList[[zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/base.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.androidthings.assistant-IkF0NX0_a0U8gM4QJbJPQw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

**Comment by Fleker** [comment]
Are you running this with the most recent version of Android Things (1.0.x) on your board?

**Comment by CometInfosoft** [comment]
yes, below you can see.

implementation 'com.google.android.things:androidthings:1.0'

**Comment by Fleker** [comment]
Which version of Android Things is on your board?

**Comment by CometInfosoft** [comment]
board means, google assistant board you said?

**Comment by Fleker** [comment]
Your imx7 Pico kit or Raspberry Pi.

**Comment by 2014james** [comment]
I also report errors on my mobile phone like this

**Comment by Fleker** [comment]
If you are trying to run this on a non-Android Things board, you will need to clean up the project dependencies, removing all libraries and code references to com.google.android.things.*

This project is intended only for Android Things, so this issue will be closed.
